### ISSUE TITLE
Question: I already had pacman packages before

### ISSUE THREAD

**Issue by ovflowd** [ValShaped/rwfus#24] opened 2023-01-22 12:36 UTC
So, I only discovered this now, and I already had packages installed before. Once I ran `rwfus -iI` (and everything went well, on the `dev` branch, `main` just fails), I noticed that all my previous pacman packages were still there. (E.g. `visual-studio-code-insiders-bin` which I installed with `makepkg`).

Question is: Is this normal behaviour? Does that mean those packages are already safe?
Question 2: Do I need to mount `rwfus` on every boot or is that done automatically?

**Comment by ValShaped** [comment] 2023-01-25 04:05
Thanks for trying out Rwfus! I worked around a bug where Rwfus would attempt to mount an overlay on top of a case-folded filesystem (which overlayFS will reject) a while back on dev; I've been meaning to push the fix to main, but I haven't been able to dedicate as much time as I'd like to Rwfus.

That said, I do have answers for your questions:

> Is this normal behaviour? Does that mean those packages are already safe?

Yes, that's correct behavior. Overlayfs is like laying a sheet of tracing paper over the filesystem; you can see the files under it, unless they're covered up by another file with the same path. The packages you've already installed are in the underlying filesystem, and aren't safe from being removed during a SteamOS update.

> Do I need to mount rwfus on every boot or is that done automatically?

Running `rwfus -i` will drop a systemd service in /etc/systemd/system and enable it. Mounting happens pretty early during boot, before almost anything else.

**Comment by ovflowd** [comment] 2023-01-25 15:32
> I've been meaning to push the fix to main, but I haven't been able to dedicate as much time as I'd like to Rwfus.

Gotcha, I'll keep an eye on the repository :) 

> Yes, that's correct behavior. Overlayfs is like laying a sheet of tracing paper over the filesystem; you can see the files under it, unless they're covered up by another file with the same path. The packages you've already installed are in the underlying filesystem, and aren't safe from being removed during a SteamOS update.

Meaning pretty much I need to uninstall those packages first, right?

> Running rwfus -i will drop a systemd service in /etc/systemd/system and enable it. Mounting happens pretty early during boot, before almost anything else.

Good to know!

Besides of that, I'm actually facing an issue when I'm trying to do `pacman -S base-devel` (reinstall the package group), as it says some directories have mismatching permissions, and then the command fails (without really explaining what went wrong)

**Comment by ValShaped** [comment] 2023-01-26 03:29
> Meaning pretty much I need to uninstall those packages first, right?

Just reinstalling the packages with Rwfus active (or copying them into the upperdir for `/usr/`; default is `/opt/rwfus/mount/upper/usr/...`) will work. 

> ...some directories have mismatching permissions...

That's one I haven't seen before. I guess Rwfus makes no attempt to keep permissions consistent, but overlayfs should hide all that, as far as I know? The issue is mentioned here: https://bbs.archlinux.org/viewtopic.php?id=245014 and apparently occurs if the package changes file permissions from one version to the next.

**Comment by ValShaped** [comment] 2023-02-06 08:39
Since (aside from elevating on startup and setting up pacman,) nothing in Rwfus directly interacts with permissions, I'm closing this issue. If it comes up again I'd like to know.

**Closed by ValShaped** 2023-02-06 08:39 UTC
Labels: question
