### ISSUE TITLE
Fails on New Deck Update SteamOS 3.5.5

### ISSUE THREAD

**Issue by DanielF823** [ValShaped/rwfus#44] opened 2023-11-17 19:04 UTC
I have noticed that a lot of things have stopped working since last night's SteamOS 3.5.5 Update

Seems I cannot re-install anything now either
(This is on top of PACMAN corrupt/Untrusted Keys from publishers of like every major dependency)

(deck@steamdeck rwfus)$ sudo ./rwfus -i
Creating overlays for /usr /etc/pacman.d /var/lib/pacman /var/cache/pacman:
0. Disabling service
1. Creating directories...
2. Updating disk image...
3. Generating service...
4. Storing configuration...
5. Copying service to /etc/systemd/system
6. Enabling service unit
Error when enabling service. See /var/log/rwfus.log for information.
× rwfusd.service - Rwfus: Carry Pacman across SteamOS updates!
     Loaded: loaded (/etc/systemd/system/rwfusd.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Fri 2023-11-17 10:50:41 PST; 52ms ago
    Process: 18221 ExecStart=/opt/rwfus/service/rwfusd.sh --start (code=exited, status=1/FAILURE)
   Main PID: 18221 (code=exited, status=1/FAILURE)
        CPU: 135ms
Log saved to /var/log/rwfus.log

**Comment by BlindingDark** [comment] 2023-11-18 07:41
https://github.com/ValShaped/rwfus/issues/33

**Comment by Ayuei** [comment] 2023-11-18 09:52
Had the same issue. What fixed it for me was to use ```sudo ./rwfus -u``` instead of the default instructions with the [latest release](https://github.com/ValShaped/rwfus/releases/tag/v0.4.2).

**Comment by ValShaped** [comment] 2024-02-11 00:08
Duplicate of #33, fixed in prerelease.

**Closed by ValShaped** 2024-02-11 00:08 UTC
