### ISSUE TITLE
install failed on brand new Deck

### ISSUE THREAD

**Issue by StoneMoe** [ValShaped/rwfus#19] opened 2022-12-05 09:17 UTC
```
(deck@steamdeck rwfus)$ ./rwfus --install
This command must be performed as root
Creating overlays for /usr /etc/pacman.d /var/lib/pacman /var/cache/pacman:
1. Generating directories
2. Generating disk image
3. Generating service
4. Storing configuration
5. Copying service to /etc/systemd/system
6. Enabling service unit
Error when enabling service. See /tmp/rwfus.O0vb.log for information.
× rwfusd.service - Rwfus: Carry Pacman across SteamOS updates!
     Loaded: loaded (/etc/systemd/system/rwfusd.service; enabled; vendor preset: disabled)
     Active: failed (Result: timeout) since Mon 2022-12-05 17:10:58 CST; 24ms ago
    Process: 6815 ExecStart=/opt/rwfus/service/rwfusd.sh --start (code=killed, signal=TERM)
   Main PID: 6815 (code=killed, signal=TERM)
        CPU: 68ms
Log saved to /tmp/rwfus.O0vb.log
```
```
(deck@steamdeck rwfus)$ cat /tmp/rwfus.O0vb.log
Rwfus v0.4.0 
Carry Pacman across SteamOS updates!

Rwfus directory: /opt/rwfus
Unit Storage directory: /opt/rwfus/service
Systemd directory: /etc/systemd/system

./rwfus --install
Loading config file /etc/opt/rwfus.conf
> Base_Directory: "/opt/rwfus"
> Directories: "/usr /etc/pacman.d /var/lib/pacman /var/cache/pacman"
> Mount_Options: "loop,compress"

Creating overlays for /usr /etc/pacman.d /var/lib/pacman /var/cache/pacman:
1. Generating directories
mkdir: created directory '/opt/rwfus/service'
2. Generating disk image
btrfs-progs v5.16 
See http://btrfs.wiki.kernel.org for more information.

NOTE: several default settings have changed in version 5.15, please make sure
      this does not affect your deployments:
      - DUP for metadata (-m dup)
      - enabled no-holes (-O no-holes)
      - enabled free-space-tree (-R free-space-tree)

Label:              Rwfus
UUID:               bd29e6ac-f378-493e-830b-25397c228fea
Node size:          4096
Sector size:        4096
Filesystem size:    8.00GiB
Block group profiles:
  Data+Metadata:    single            8.00MiB
  System:           single            4.00MiB
SSD detected:       no
Zoned device:       no
Incompat features:  mixed-bg, extref, skinny-metadata, no-holes
Runtime features:   free-space-tree
Checksum:           crc32c
Number of devices:  1
Devices:
   ID        SIZE  PATH
    1     8.00GiB  /opt/rwfus/rwfus.btrfs

mount: /dev/loop1 mounted on /opt/rwfus/mount.
Resize device id 1 (/dev/loop1) from 8.00GiB to max
mkdir: created directory '/opt/rwfus/mount/upper'
mkdir: created directory '/opt/rwfus/mount/upper/usr'
mkdir: created directory '/opt/rwfus/mount/work'
mkdir: created directory '/opt/rwfus/mount/work/usr'
mkdir: created directory '/opt/rwfus/mount/upper/etc-pacman.d'
mkdir: created directory '/opt/rwfus/mount/work/etc-pacman.d'
mkdir: created directory '/opt/rwfus/mount/upper/var-lib-pacman'
mkdir: created directory '/opt/rwfus/mount/work/var-lib-pacman'
mkdir: created directory '/opt/rwfus/mount/upper/var-cache-pacman'
mkdir: created directory '/opt/rwfus/mount/work/var-cache-pacman'
umount: /home/.steamos/offload/opt/rwfus/mount (/dev/loop1) unmounted
3. Generating service
Generating service rwfusd
  script /opt/rwfus/service/rwfusd.sh
  unit   /opt/rwfus/service/rwfusd.service
4. Storing configuration
Storing config file to /etc/opt/rwfus.conf...
-rw-r--r-- 1 root root 574 Dec  5 17:10 /etc/opt/rwfus.conf
5. Copying service to /etc/systemd/system
'/opt/rwfus/service/rwfusd.service' -> '/etc/systemd/system/rwfusd.service'
6. Enabling service unit
Created symlink /etc/systemd/system/multi-user.target.wants/rwfusd.service → /etc/systemd/system/rwfusd.service.
Job for rwfusd.service failed because a timeout was exceeded.
See "systemctl status rwfusd.service" and "journalctl -xeu rwfusd.service" for details.
Error when enabling service. See /tmp/rwfus.O0vb.log for information.
```
```
(deck@steamdeck rwfus)$ sudo journalctl -xeu rwfusd.service
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit rwfusd.service has begun execution.
░░ 
░░ The job identifier is 4194.
Dec 05 17:10:55 steamdeck rwfusd.sh[6815]: Rwfus v0.4.0
Dec 05 17:10:55 steamdeck rwfusd.sh[6815]: Carry Pacman across SteamOS updates!
Dec 05 17:10:55 steamdeck rwfusd.sh[6815]: /opt/rwfus/service/rwfusd.sh --start --
Dec 05 17:10:55 steamdeck rwfusd.sh[6815]: Loading config file /etc/opt/rwfus.conf
Dec 05 17:10:55 steamdeck rwfusd.sh[6815]: > Base_Directory: "/opt/rwfus"
Dec 05 17:10:55 steamdeck rwfusd.sh[6815]: > Directories: "/usr /etc/pacman.d /var/lib/pacman /var/cache/pacman"
Dec 05 17:10:55 steamdeck rwfusd.sh[6815]: > Mount_Options: "loop,compress"
Dec 05 17:10:55 steamdeck rwfusd.sh[6817]: Created symlink /etc/systemd/system/pacman-cleanup.service → /dev/null.
Dec 05 17:10:56 steamdeck rwfusd.sh[6837]: mount: /dev/loop1 mounted on /opt/rwfus/mount.
Dec 05 17:10:56 steamdeck rwfusd.sh[6857]: Resize device id 1 (/dev/loop1) from 8.00GiB to max
Dec 05 17:10:56 steamdeck rwfusd.sh[6815]: Creating overlay (/opt/rwfus/mount/upper/usr, /opt/rwfus/mount/work/usr) on /usr
Dec 05 17:10:56 steamdeck rwfusd.sh[6860]: mount: overlay mounted on /usr.
Dec 05 17:10:56 steamdeck rwfusd.sh[6815]: Successfully overlaid /opt/rwfus/mount/upper/usr on /usr
Dec 05 17:10:56 steamdeck rwfusd.sh[6815]: Creating overlay (/opt/rwfus/mount/upper/etc-pacman.d, /opt/rwfus/mount/work/etc-pacman.d) on /etc/pacman.d
Dec 05 17:10:56 steamdeck rwfusd.sh[6862]: mount: /etc/pacman.d: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.
Dec 05 17:10:56 steamdeck rwfusd.sh[6815]:   /etc/pacman.d not available (error 0). Retrying...
Dec 05 17:10:58 steamdeck systemd[1]: rwfusd.service: start operation timed out. Terminating.
Dec 05 17:10:58 steamdeck systemd[1]: rwfusd.service: Main process exited, code=killed, status=15/TERM
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
```
```
(deck@steamdeck rwfus)$ lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
loop0         7:0    0    8G  0 loop /home/.steamos/offload/opt/rwfus/mount
                                     /opt/rwfus/mount
loop1         7:1    0    8G  0 loop /home/.steamos/offload/opt/rwfus/mount
                                     /opt/rwfus/mount
nvme0n1     259:0    0 57.6G  0 disk 
├─nvme0n1p1 259:1    0   64M  0 part 
├─nvme0n1p2 259:2    0   32M  0 part 
├─nvme0n1p3 259:3    0   32M  0 part 
├─nvme0n1p4 259:4    0    5G  0 part /
├─nvme0n1p5 259:5    0    5G  0 part 
├─nvme0n1p6 259:6    0  256M  0 part /var
├─nvme0n1p7 259:7    0  256M  0 part 
└─nvme0n1p8 259:8    0   47G  0 part /var/tmp
                                     /var/log
                                     /var/lib/systemd/coredump
                                     /var/lib/flatpak
                                     /var/lib/docker
                                     /var/cache/pacman
                                     /srv
                                     /root
                                     /opt
                                     /home
```

**Comment by StoneMoe** [comment] 2022-12-05 09:17
```
Operating System: SteamOS 3.3.2
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-valve21.3-1-neptune (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Custom APU 0405
Memory: 14.5 GiB of RAM
Graphics Processor: AMD Custom GPU 0405
```

**Comment by dayue1984** [comment] 2022-12-06 01:20
same here

**Comment by StoneMoe** [comment] 2022-12-06 03:34
casefold is enabled on home partition
```
(deck@steamdeck ~)$ sudo tune2fs -l /dev/nvme0n1p8 | grep casefold
Filesystem features:      has_journal ext_attr resize_inode dir_index filetype needs_recovery extent 64bit flex_bg casefold sparse_super large_file huge_file dir_nlink extra_isize metadata_csum
```

**Comment by StoneMoe** [comment] 2022-12-06 03:36
maybe duplicated with https://github.com/ValShaped/rwfus/issues/12
I'll close it for now.

**Comment by ValShaped** [comment] 2022-12-10 02:58
Hey, sorry for not seeing this earlier! Rwfus is failing to install because it hits the max number of mounts allowed on one mountpoint. I've instituted a workaround in the dev branch. Could you retest from there?

**Comment by StoneMoe** [comment] 2022-12-13 03:25
```
deck@steamdeck /o/rwfus (dev)> ./rwfus -iI
This command must be performed as root
Creating overlays for /usr /etc/pacman.d /var/lib/pacman /var/cache/pacman:
find: ‘/opt/rwfus/service’: No such file or directory
1. Creating directories...
2. Generating disk image...
3. Generating service...
4. Storing configuration...
5. Copying service to /etc/systemd/system
6. Enabling service unit
7. Setting up pacman...
Done!

● rwfusd.service - Rwfus: Carry Pacman across SteamOS updates!
     Loaded: loaded (/etc/systemd/system/rwfusd.service; enabled; vendor preset: disabled)
     Active: active (exited) since Tue 2022-12-13 11:24:02 CST; 39s ago
    Process: 73330 ExecStart=/opt/rwfus/service/rwfusd.sh --start (code=exited, status=0/SUCCESS)
   Main PID: 73330 (code=exited, status=0/SUCCESS)
        CPU: 165ms
Stopping Rwfus
Adding Rwfus to /home/.steamos/offload/usr/local/bin
Unmasking and enabling usr-local.mount
Restarting Rwfus
Done!

Log saved to /var/log/rwfus.log
deck@steamdeck /o/rwfus (dev)> 

```
@ValShaped I reimaged my deck and retested.

**Comment by ValShaped** [comment] 2022-12-13 03:36
@StoneMoe Yes, that means Rwfus is working. The first block of output (Creating directories->Done!) corresponds with installing and enabling Rwfus. It then prints the status of `rwfusd`, the service that mounts and unmounts the overlays. All that corresponds to `rwfus -i` (install)
The second block (Stopping Rwfus ... Done!) corresponds to `rwfus -I`, which puts Rwfus in the SteamOS Offload directory for /usr/local/bin, which allows you to use the manager (`rwfus`) from anywhere, even when rwfus isn't enabled.

Thanks for testing! I'll re-close the issue, and as soon as I can verify that the changes in 0.4.1-prerelease are working as intended, I'll push the changes to main. If you find any other issues, I'll be happy to help resolve them!

**Closed by ValShaped** 2022-12-13 03:36 UTC

**Comment by GingerBobRoss** [comment] 2023-01-03 08:51
I also have a similar issue when trying to install rwfus.
The install itself goes through, but the service itself will not start due to a timeout.
[rwfus.4WVG.log](https://github.com/ValShaped/rwfus/files/10335217/rwfus.4WVG.log)

**Comment by ValShaped** [comment] 2023-01-04 19:16
@GingerBobRoss Please retry with dev branch:
`git clone -b dev git@github.com:ValShaped/rwfus.git`
